### ISSUE TITLE
JDBC causing significant lag in 1.14.4

### ISSUE THREAD

**Issue by k-jiang** [AddstarMC/Prism-Bukkit#47]
Prism locked the main thread and freeze the whole server 10-25 seconds everytimes when a player join the game:
```
[07:51:09] [LoginProcessingThread/INFO]: UUID of player kjiang is xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[07:51:19] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-192 (MC: 1.14.4) ---
[07:51:19] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[07:51:19] [Paper Watchdog Thread/ERROR]: ------------------------------
[07:51:19] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[07:51:19] [Paper Watchdog Thread/ERROR]: The server is waiting on these chunks: []
[07:51:19] [Paper Watchdog Thread/ERROR]: ------------------------------
[07:51:19] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[07:51:19] [Paper Watchdog Thread/ERROR]: 	PID: 31 | Suspended: false | Native: true | State: TIMED_WAITING
[07:51:19] [Paper Watchdog Thread/ERROR]: 	Stack:
[07:51:19] [Paper Watchdog Thread/ERROR]: 		sun.misc.Unsafe.park(Native Method)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.FairBlockingQueue.poll(FairBlockingQueue.java:151)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:650)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:188)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:128)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		me.botsko.prism.database.sql.SQLPrismDataSource.getConnection(SQLPrismDataSource.java:72)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		me.botsko.prism.players.PlayerIdentification.lookupByUUID(PlayerIdentification.java:396)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		me.botsko.prism.players.PlayerIdentification.getPrismPlayer(PlayerIdentification.java:120)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		me.botsko.prism.players.PlayerIdentification.cachePrismPlayer(PlayerIdentification.java:28)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		me.botsko.prism.listeners.PrismPlayerEvents.onPlayerJoin(PrismPlayerEvents.java:121)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor810.execute(Unknown Source)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.EventExecutor$$Lambda$3015.0000000075701030.execute(Unknown Source)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:191)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:138)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.joinWorld(AbstractLoginListenerPlay.java:142)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.lambda$finishLogin$1(AbstractLoginListenerPlay.java:90)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay$$Lambda$4484.00000000B8514780.call(Unknown Source)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.FutureTask.run(FutureTask.java:266)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1161)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919)
[07:51:19] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:819)
[07:51:19] [Paper Watchdog Thread/ERROR]: ------------------------------
[07:51:19] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[07:51:19] [Paper Watchdog Thread/ERROR]: ------------------------------
```
A player would join the game at 07:51:09, then the server will only be responsive at 07:51:09 and throw an expression. Sometimes the expression above repeated 3 times with 5 seconds delay in between.

Since our server has players join and quit constantly, it causing the server extremely laggy and nearly crashed our network.

Confirmed with Paper 1.14.4 build 192
Prism 45a8f07.
WorldEdit 7.0.1
WorldGuard 7.0.1

I will try to use d78eac4 and see if things getting better.

P.S. I appreciate all of you continue supporting the Prism-Bukkit project. Prism is the ultimate logging plugin and you guys / girls are awesome! We are heavily depend on it and it is nearly impossible to switch. Once again thank you all for the effort!

**Comment by k-jiang** [comment]
Not sure if it is related but sometimes the server also throw this expression:
```
[07:14:41] [Craft Scheduler Thread - 187/INFO]: [Prism] Could not retreive a connection
[07:14:41] [Craft Scheduler Thread - 187/WARN]: java.sql.SQLException: No Connection to database
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at me.botsko.prism.database.sql.SQLInsertBuilder.createBatch(SQLInsertBuilder.java:90)
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at me.botsko.prism.actionlibs.RecordingTask.insertActionsIntoDatabase(RecordingTask.java:98)
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at me.botsko.prism.actionlibs.RecordingTask.save(RecordingTask.java:40)
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at me.botsko.prism.actionlibs.RecordingTask.run(RecordingTask.java:148)
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at java.lang.Thread.run(Thread.java:819)
[07:14:41] [Craft Scheduler Thread - 187/ERROR]: [Prism] Database connection error: No Connection to database
[07:14:41] [Craft Scheduler Thread - 187/WARN]: java.sql.SQLException: No Connection to database
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at me.botsko.prism.database.sql.SQLInsertBuilder.createBatch(SQLInsertBuilder.java:90)
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at me.botsko.prism.actionlibs.RecordingTask.insertActionsIntoDatabase(RecordingTask.java:98)
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at me.botsko.prism.actionlibs.RecordingTask.save(RecordingTask.java:40)
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at me.botsko.prism.actionlibs.RecordingTask.run(RecordingTask.java:148)
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[07:14:41] [Craft Scheduler Thread - 187/WARN]: 	at java.lang.Thread.run(Thread.java:819)
```
We use a dedicated MySQL server connected through TCP. This server located in the same datacenter with ~0.2ms latency. 

For some reason. Prism seems continually creating connection.

MySQL status:
```
mysql> show status like 'Connections';
+-----------------------------------------------+---------------------+
| Variable_name                                 | Value               |
+-----------------------------------------------+---------------------+
| Connections                                   | 6690                |
+-----------------------------------------------+---------------------+
```
MySQL variables:
```
mysql> show variables like '%connect%';
+-----------------------------------------------+-----------------+
| Variable_name                                 | Value           |
+-----------------------------------------------+-----------------+
| character_set_connection                      | utf8            |
| collation_connection                          | utf8_general_ci |
| connect_timeout                               | 10              |
| disconnect_on_expired_password                | ON              |
| init_connect                                  | SET NAMES utf8  |
| max_connect_errors                            | 100             |
| max_connections                               | 151             |
| max_user_connections                          | 0               |
| performance_schema_session_connect_attrs_size | 512             |
+-----------------------------------------------+-----------------+
```

config.yml
```
  mysql:
    hostname: x.x.x.x
    username: xxxx
    password: xxxx
    databaseName: xxxx
    prefix: prism_
    port: '3306'
    useNonStandardSql: true
    database:
      max-pool-connections: 20
      pool-initial-size: 10
      max-idle-connections: 10
      max-wait: 30000
      max-failures-before-wait: 5
      actions-per-insert-batch: 300
      force-write-queue-on-shutdown: true
```

Connection leak?

**Comment by k-jiang** [comment]
update: d78eac4 is not working.

**Comment by AmauryCarrade** [comment]
Hello! I'm having the same problem as @k-jiang on my server (latest Paper as of today, 1.14.4), except for the connection lag, at least until now.

There's a _LOT_ of connections to the MySQL server:

```
MariaDB [(none)]> SHOW STATUS LIKE 'Connections';
+---------------+--------+
| Variable_name | Value  |
+---------------+--------+
| Connections   | 478406 |
+---------------+--------+
1 row in set (0.000 sec)
```

and I'm experiencing frequent “Database connection error: No Connection to database” errors in the console (I suspect potential data loss, but I'm not sure):

```
[00:07:56 ERROR]: [Prism] Database connection error: No Connection to database
[00:07:56 WARN]: java.sql.SQLException: No Connection to database
[00:07:56 WARN]:        at me.botsko.prism.database.sql.SQLInsertBuilder.createBatch(SQLInsertBuilder.java:90)
[00:07:56 WARN]:        at me.botsko.prism.actionlibs.RecordingTask.insertActionsIntoDatabase(RecordingTask.java:98)
[00:07:56 WARN]:        at me.botsko.prism.actionlibs.RecordingTask.save(RecordingTask.java:40)
[00:07:56 WARN]:        at me.botsko.prism.actionlibs.RecordingTask.run(RecordingTask.java:148)
[00:07:56 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[00:07:56 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[00:07:56 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:07:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[00:07:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[00:07:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:835)
```

I built the latest Prism commit today.

**Comment by Bobcat00** [comment]
Yes, I am also getting 'No Connection to database' errors every few minutes:
```
2020-01-02 14:30:44 [WARN] java.sql.SQLException: No Connection to database
2020-01-02 14:30:44 [WARN] 	at me.botsko.prism.database.sql.SQLInsertBuilder.createBatch(SQLInsertBuilder.java:90)
2020-01-02 14:30:44 [WARN] 	at me.botsko.prism.actionlibs.RecordingTask.insertActionsIntoDatabase(RecordingTask.java:98)
2020-01-02 14:30:44 [WARN] 	at me.botsko.prism.actionlibs.RecordingTask.save(RecordingTask.java:40)
2020-01-02 14:30:44 [WARN] 	at me.botsko.prism.actionlibs.RecordingTask.run(RecordingTask.java:148)
2020-01-02 14:30:44 [WARN] 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
2020-01-02 14:30:44 [WARN] 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
2020-01-02 14:30:44 [WARN] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-01-02 14:30:44 [WARN] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-01-02 14:30:44 [WARN] 	at java.lang.Thread.run(Thread.java:748)
```
Previously, I was using a version of Prism from Feb 23, 2018 with 1.12.2.  This worked fine with the same MySQL server.  There were no connection problems.

It also seems that queries are much, much slower than they used to be.

**Comment by AmauryCarrade** [comment]
I'm working on a fork fixing such connection problems (for 1.14.4 & 1.15.1+). The connection lag is indeed from Prism (database connection to load the Prism internal player ID from the main thread).

**Comment by Bobcat00** [comment]
Whatever it's doing, it shouldn't take 25 seconds, as the MySQL server is on the same machine.  I'm thinking of going back before they started messing with the database setup and manually applying all the other changes.  The plugin is not usable in its current state.

**Comment by Bobcat00** [comment]
Note to self: Maybe go back to Jan 5, 2019 (a year ago!) and selectively apply commits from then.

**Comment by addstar** [comment]
Apologies for not commenting sooner on this PR, we're aware that this Prism fork has been unstable for a while. Unfortunately all changes are after 72264607f4c1be92d3c8d856056f5f3c12b7363f are untested and it has been neglected for a long time. We're still running that version on all our servers (https://jenkins.addstar.com.au/job/Prism-Bukkit/35/), and we didn't realise anyone was using this fork, in hindsight all the DB work should have been in a dev branch.

I don't know why the connection would lock up for 25 but I can tell you a **_huge_** amount of DB related stuff has been changed since that commit and it's all mostly untested.. or tested and horribly broken.

Right now all I can say is that we want to continue working on it and it is causing us some issues with 1.14/1.15 updates but we haven't had time to fix the major changes we started, let alone add fixes for newer MC versions. Sorry for the bad news, but I really hope we can get back to this and get it all working well again.

**Comment by Bobcat00** [comment]
Thanks for that update.  It gives us a place to start.  I have been using Prism with 1.12.2 quite successfully, and even made [a number of my own corrections](https://github.com/Bobcat00/Prism-Bukkit/commits/1-12-2), including fixing the ore alerts.

I switched to 1.15.1 on Jan 1, and that's when the problems began.  Prism is light years ahead of the others.  I really appreciate the work you've done on it over the years.  It's been a life saver.

**Comment by addstar** [comment]
Oh that's good to hear, we also have had great success with Prism prior to 1.13. We decided to redo a lot of things in 1.13 because of the considerable item name/meta changes and it became a big task which unfortunately we got side tracked and hasn't been worked on in a while.

We happily welcome PRs to our fork and would love to combine our efforts to make Prism better! :grin: Even that old version from May 2019 is pretty buggy and problematic, but we're currently running it on all our 1.14.4/1.15 servers, since we have nothing else.

Our fork is definitely not dead - We still love Prism and have all intentions of updating it, but it has been a matter of lack of time. If you (or anyone else) is interested in helping improve it, that would be awesome!

**Comment by AmauryCarrade** [comment]
Wonderful to hear! I'm currently trying to fix the database and performance issues for my server, I could share the work (but I introduced a new personal dependency to handle worker threads).

**Comment by addstar** [comment]
Oh I see, the `ANY_VALUE` function was only introduced in 5.7. We've been using 5.7 for quite a long time so I didn't realise we have introduced functionality that is not available in earlier versions.

We could re-write those queries (there are several) to not use those features, but it would be a bit of work. In all honesty, we probably shouldn't be using that function anyway, it's a little bit of a misuse of SQL but it let's us do things that are otherwise more complex to do.

If you can use MySQL 5.7, that would very likely fix most of your problems. If not, the only way to make this work is to implement backward-compatible changes. Basically, it means our Prism is currently _only_ compatible with MySQL 5.7.

**Comment by Bobcat00** [comment]
At home where I run my test server, I'm using 5.6.11, which I installed in 2013.  My host uses 5.7.28, so I'll just continue testing with their DB.

**Comment by Bobcat00** [comment]
OK, now we're cooking with gas! I have this thing working pretty well on 1.15.1.  I fixed a few things, like the ore and block alerts, and a problem with the purge permissions.  You can check out my changes at https://github.com/Bobcat00/Prism-Bukkit/commits/1-15-1-190529 I tested my changes on my test server, and have just now put it on the real server.

Thanks again for your help!

**Comment by addstar** [comment]
Good to hear! Are you running the latest builds or did you branch from https://github.com/AddstarMC/Prism-Bukkit/commit/72264607f4c1be92d3c8d856056f5f3c12b7363f ?

**Comment by Bobcat00** [comment]
I branched from 7226460.  I cherry-picked a couple newer commits to fix the logging of air drops.  This is working well.  Ran timings and I don't see any lag or stalls.  I'm not clear about the Paper vs Spigot repos, but I got it to work with Spigot 1.15.1.

I just blunder my way through git, but it seems to me you could reset HEAD back to 7226460 and put all these broken/untested commits in a new branch.  I know that has some side effects you have to watch out for.  But what you have there doesn't work, and I don't see the value in keeping it on the master branch.

**Comment by TNTUP** [comment]
Subscribing here, looks promising! Glad Prism is still alive! Missed it!!

**Comment by TNTUP** [comment]
I'm getting the same issue about the FUNCTION thing any_value, running on MariaDB 10.3.15-MariaDB - mariadb.org binary distribution from XAMPP on Windows. Not sure if its safe to update MariaDB within XAMPP installation (not sure if by copying to it would work)

**Comment by addstar** [comment]
@Bobcat00 My latest change has updated Prism for 1.15 and fixed a few issues. There's still an issue with the DB sometimes disconnecting/reconnecting (seems like a DB pooling issue) which I'll investigate and try to fix, but besides that, this latest version is working pretty well for a 1.15.2 test server (tested many blocks, lookups and rollbacks.. all working properly).

There's also an issue where it doesn't generate a good default config, I'll fix that soon too... but making good progress! :grin:

**Comment by addstar** [comment]
By the way, it still only support MySQL 5.7 and I don't think we'll bother changing that.

So @TNTUP you should use whichever version equivalent that would be for MariaDB (I don't use it so I'm not sure). It just needs to be a version that supports the `ANY_VALUE()` function.

**Comment by addstar** [comment]
> There's also an issue where it doesn't generate a good default config, I'll fix that soon too... but making good progress!

Oh! I just tested this and it should generate a new valid config if one doesn't exist. So if you want to try it, I'd suggest renaming your current one, letting it generate a new one and updating as necessary! :tada:

**Comment by TNTUP** [comment]
> By the way, it still only support MySQL 5.7 and I don't think we'll bother changing that.
> 
> So @TNTUP you should use whichever version equivalent that would be for MariaDB (I don't use it so I'm not sure). It just needs to be a version that supports the `ANY_VALUE()` function.

Sadly with MariaDB this is not possible for me. I'm on the XAMPP on my Windows system and MariaDB I guess its far better than MySQL (I'm probably wrong) so I'll stick with CP then. As soon I go back to linux I'll check by installing MySQL 5.7+ or higher^^

**Comment by Bobcat00** [comment]
There were so many problems with the later commits, that I'm reluctant to try them again.  I'm running from your version of May 29, with several fixes of my own https://github.com/Bobcat00/Prism-Bukkit/commits/1-15-1-190529

My biggest problem right now is lookups saying the player used air or dropped air. Not sure where they're coming from. I was also getting a NPE in ItemStackAction, so maybe that's related.

MySQL 5.7 is fine by me.

**Comment by addstar** [comment]
I've made some major changes (will commit them today) to greatly improve performance and resolve all the DB issues. I switched to using HikariCP for database pooling which is widely known to be a far better connection pooling framework than the standard apache jdbc one, which helped me identify and fix connection leaks which were causing the issues with connections and lag.

We've been doing some extensive testing (with staff) on a test server and we'll be going live on this one with a new server in coming days. So far it's 100% working with no errors, everything we've tested has tracked and rolled back correctly.. so going forward, this is the one we'll be using.

I'd highly recommend trying it and I think we'd both gain benefits from sharing the same version since we could contribute to it together :)

**Comment by Bobcat00** [comment]
Do the ore alerts work?  Because that was one of the problems I fixed.  Not to mention a problem with purging.

**Comment by addstar** [comment]
@Bobcat00 Oh? I'll have to look through your commits and see which ones should be applied in our fork too. Also feel free to point out the SHAs or even PR them here. Instead of us maintaining separate forks, would you be interested in combining efforts and working on the same one?

Also I haven't tried ore alerts since we don't use them. But I can do some testing when I get time.

**Comment by Bobcat00** [comment]
For the alerts, you also need an updated config:
```
      blocks:
        diamond_ore: '&b'
        gold_ore: '&6'
        iron_ore: '&7'
        emerald_ore: '&a'
        lapis_ore: '&9'
```
```
      item-placement:
      - bedrock
      - sticky_piston
      - tnt
      - flowing_lava
      - lava
```

**Comment by addstar** [comment]
I've never used the ore alert and I've configured it as you mentioned, I also cherry-picked your commit (https://github.com/Bobcat00/Prism-Bukkit/commit/32f474f3510916c4adbab54b611f277f5cd4e313) but I still don't get alerts when I mine diamond ore. Is that how it's meant to work?

**Comment by addstar** [comment]
Oh nvm, I figured it out.. it was because of my perms. I got someone else to try and alerts worked fine.. although the colours didn't work, but I can fix that.

**Comment by Bobcat00** [comment]
The alert colors work in-game. Don't know about the console.

![ore_alerts](https://user-images.githubusercontent.com/3617206/73372434-34ac1d80-4285-11ea-91f7-ff9a3a4f006f.png)

**Comment by Bobcat00** [comment]
OK, I successfully compiled and ran your new version.  I already see some problems that I fixed in my fork.  Do you want me to add changes and do pull requests?  Do you want me to write matching issues for them?

I kind of blunder my way around git/github, but I usually manage to do things the right way.

**Comment by addstar** [comment]
@TNTUP while I was redoing the DB code recently, I noticed the option `useNonStandardSql`. You should try setting that to `false` and see if it resolves your issues with not being MySQL 5.7.

**Comment by addstar** [comment]
I'm closing this issue for now, as it's resolved in the latest build. Thanks everyone for your feedback and efforts. Please open _new_ issues with specific all necessary info if you have further problems.

@Bobcat00 we can continue to discuss things on SpigotMC :)

**Comment by TNTUP** [comment]
> @TNTUP while I was redoing the DB code recently, I noticed the option `useNonStandardSql`. You should try setting that to `false` and see if it resolves your issues with not being MySQL 5.7.

Ah! I've seen this setting somewhere on someone else's Prism fork! Completely forgot that xD
